### ISSUE TITLE
language clean-up

### ISSUE THREAD

**Issue by jonz-secops** [assafmo/IsTorExit#3]
If it could be made more clear, it would be helpful.

what is meant by destination IP/port?

Thanks.

**Comment by assafmo** [comment]
Yeah you're right, it's also not that clear in the original TOR docs.

Basically we are trying to exit the TOR network via the IP we're testing to the destination IP and port.

For better UX, by default I set the destination IP and port to a Google server which is always up and available.

For more info on how the code works you can see https://2019.www.torproject.org/projects/tordnsel.html.en

I'll try today to better explain this in the readme as well.

**Comment by assafmo** [comment]
Added an explanation and examples in the readme:
https://github.com/assafmo/IsTorExit/blob/v0.9.4/README.md#how-this-works
